export { default as Home } from './Home'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Unauthorized } from './Unauthorized'
export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
export { default as Office } from './Office'
